### ISSUE TITLE
Compiling on Mac OS X 10.6.7 Fails

### ISSUE THREAD

**Issue by joemccann** [creationix/node-leveldb#3]
Have a look:
<code>
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for gcc                         : ok  
Checking for node path                   : ok /Users/joemccann718/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.070s)
Waf: Entering directory `/Users/joemccann718/Documents/workspace/node-leveldb/build'
[ 1/72] cxx: deps/leveldb/db/builder.cc -> build/default/deps/leveldb/db/builder_1.o
cc1plus: error: unrecognized command line option "-std=c++0x"
[ 2/72] cxx: deps/leveldb/db/db_impl.cc -> build/default/deps/leveldb/db/db_impl_1.o
[ 3/72] cxx: deps/leveldb/db/db_iter.cc -> build/default/deps/leveldb/db/db_iter_1.o
cc1plus: error: unrecognized command line option "-std=c++0x"
cc1plus: error: unrecognized command line option "-std=c++0x"
Waf: Leaving directory`/Users/joemccann718/Documents/workspace/node-leveldb/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx builder.cc -> builder_1.o}
 -> task failed (err #1): 
    {task: cxx db_impl.cc -> db_impl_1.o}
 -> task failed (err #1): 
    {task: cxx db_iter.cc -> db_iter_1.o}
</code>

**Comment by creationix** [comment]
This is a known issue with leveldb.  Apple's GCC doesn't support the `-std=c++0x` option that leveldb requires.  I'm not sure what to do about it.

**Comment by joemccann** [comment]
Ahh gotcha...thx.

**Comment by creationix** [comment]
You're welcome to dig into the problem.  I don't develop on a mac.

**Comment by joemccann** [comment]
I'll take a look and see if anything is on the Google Code wiki/mailing list about it.

**Comment by joemccann** [comment]
Looks like a patch here:  https://github.com/davisp/leveldb/commit/50e280c9b1cfde0e255d124f38e1aa436d36ba52

**Comment by joemccann** [comment]
Working on porting the patch now...

**Comment by shinuza** [comment]
Please see issue 2 for the fix.
The version I've commited builds on both Mac OS X 10.6.7 and Arch Linux.

**Comment by joemccann** [comment]
Ahh nice, I just got it to build, but was debugging the wscript file.

**Comment by creationix** [comment]
@joemccann, does @shinuza's patch work for you?

**Comment by joemccann** [comment]
yup

**Comment by creationix** [comment]
closing...
